### ISSUE TITLE
All versions except 0.9.6 removed from pypi

### ISSUE THREAD

**Issue by difabion** [sigma-py/orthopy#115]
Is this expected behavior from PYPI?  We were using an older version of orthopy and we can no longer install it via `pip`.

**Comment by qishengjie9** [comment]
hello，I get into the same question.when I need pip an orthopy<0.9 ,I found there was no such package. Have you solve this question? And if you have an older  version of orthopy ,could you please share with me. Thanks a lot! My email is qishengjietju@163.com

**Comment by nschloe** [comment]
Fixed that now.
