### ISSUE TITLE
show depends on matplotx

### ISSUE THREAD

**Issue by GitHimanshuc** [sigma-py/orthopy#116]
```python
import orthopy

orthopy.c1.jacobi.show(5, "normal", 0.0, 0.0)
```
gives,
`ModuleNotFoundError: No module named 'matplotx'`

matplotx is not installed by default when installing orthopy.

**Comment by nschloe** [comment]
It's an optional dependency. You can install orthopy with
```
pip install orthopy[all]
```
to get them all.

**Comment by nschloe** [comment]
I'll just make the dependencies mandatory until someone complains. :)
